application: hotelreviews
version: 1
runtime: python37
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static
  
- url: /.*
  script: main.application
  

libraries:

- name: django
  version: "2.1"
 
env_variables:
  DJANGO_SETTINGS_MODULE: 'hotelreviews.settings'
